.PHONY: setup build clean test pre-commit

pre-commit:
	@if [ -f scripts/pre-commit ]; then \
		HOOKS_DIR=$$(git rev-parse --git-path hooks 2>/dev/null || echo ".git/hooks"); \
		mkdir -p "$$HOOKS_DIR"; \
		ln -sf ../../scripts/pre-commit "$$HOOKS_DIR/pre-commit"; \
		echo "✓ Pre-commit hook installed"; \
	else \
		echo "Error: scripts/pre-commit not found"; \
		exit 1; \
	fi

setup:
	@echo "Generating setup.sh script..."
	@echo "#!/bin/bash" > setup.sh
	@echo "# Environment setup script for C SDK" >> setup.sh
	@echo "# Generated by 'make setup'" >> setup.sh
	@echo "" >> setup.sh
	@echo "export SDK_ROOT=\"\$$(cd \"\$$(dirname \"\$$BASH_SOURCE\")\" && pwd)\"" >> setup.sh
	@echo "export SDK_INCLUDE=\"\$$SDK_ROOT/include\"" >> setup.sh
	@echo "export SDK_BUILD=\"\$$SDK_ROOT/build\"" >> setup.sh
	@echo "" >> setup.sh
	@echo "echo \"SDK environment variables set:\"" >> setup.sh
	@echo "echo \"  SDK_ROOT=\$$SDK_ROOT\"" >> setup.sh
	@echo "echo \"  SDK_INCLUDE=\$$SDK_INCLUDE\"" >> setup.sh
	@echo "echo \"  SDK_BUILD=\$$SDK_BUILD\"" >> setup.sh
	@chmod +x setup.sh
	@echo "setup.sh generated successfully"

build:
	cmake -S . -B build && cmake --build build

clean:
	if [ -d build ]; then make -C build clean; fi

test: build
	cd build && ctest --output-on-failure
